### ISSUE TITLE
proxychains 使用

### ISSUE THREAD

**Issue by HUGHNew** [chanchancl/How-to-build-a-develop-environment-for-rust#1]
既然能上GitHub的吧 默认会使用工具吧
可以选择使用 proxychains
不过对于整条的长命令 proxychains 不太好使用
可以
```bash
curl  https://sh.rustup.rs -sSf > rust.sh
proxychains sh rust.sh
rm rust.sh
```
这样就不用自己设置其他的变量了

**Comment by chanchancl** [comment]
对的，不过这里给的就是在无法使用工具的情况下，如何安装rust

以及在使用rust的过程中，如何快速下载 dependency
